FROM python:3.11-slim

WORKDIR /app

COPY telemetry/ ./telemetry
COPY docker/requirements.txt ./requirements.txt
COPY .env .env

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "telemetry/sensor_logger.py"]